# Generated by Django 4.1.5 on 2023-06-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='cuartel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bomberos.cuartel'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cuartel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bomberos.cuartel'),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre cuartel'),
        ),
    ]
