# Generated by Django 4.1.5 on 2023-06-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0002_bombero_cuartel_alter_carro_cuartel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fallas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
