# Generated by Django 4.1.5 on 2023-06-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0004_donacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hidrante',
            fields=[
                ('idHidrante', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('danado', 'Dañado'), ('falta_mantencion', 'Falta de Mantención')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='estado_hidrante',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('danado', 'Dañado'), ('falta_mantencion', 'Falta de Mantención')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='hidrante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bomberos.hidrante'),
        ),
    ]
