# Generated by Django 4.1.5 on 2023-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0005_hidrante_reportefalla_estado_hidrante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='estado_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
