from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',index, name="home"),
    path('index',index, name="home"),
    path('lista_cuarteles',lista_cuarteles,name="lista_cuarteles"),
    path('form_mod_cuartel/<id>',form_mod_cuartel,name="form_mod_cuartel"),
    path('form_del_cuartel/<id>',form_del_cuartel, name="form_del_cuartel"),
    path('form_cuartel',form_cuartel,name="form_cuartel"),
    path('lista_carros',lista_carros,name="lista_carros"),
    path('form_mod_carro/<id>',form_mod_carro,name="form_mod_carro"),
    path('form_del_carro/<id>',form_del_carro,name="form_del_carro"),
    path('form_carros',form_carro,name="form_carros"),
    path('lista_cargos',lista_cargos,name="lista_cargos"),
    path('form_mod_cargo/<id>',form_mod_cargo,name="form_mod_cargo"),
    path('form_del_cargo/<id>',form_del_cargo,name="form_del_cargo"),
    path('form_cargos',form_cargos,name="form_cargos"),
    path('lista_bomberos',lista_bomberos,name="lista_bomberos"),
    path('form_mod_bombero/<id>',form_mod_bombero,name="form_mod_bombero"),
    path('form_del_bombero/<id>',form_del_bombero,name="form_del_bombero"),
    path('form_bombero',form_bombero,name="form_bombero"),
    path('donaciones/', donaciones, name='donaciones'),
    path('agradecimiento/', agradecimiento, name='agradecimiento'),
    path('confirmar_donacion/', confirmar_donacion, name='confirmar_donacion'),
    path('nuestros_funcionarios', nuestros_funcionarios, name='nuestros_funcionarios'),
    path('nuestra_historia', nuestra_historia, name='nuestra_historia'),
    path('contacto', contacto, name='contacto'),
    path('administrador', administrador, name='contacto'),
    path('lista_emergencias', lista_emergencias, name='lista_emergencias'),
    path('form_mod_emergencia/<id>',form_mod_emergencia,name="form_mod_emergencia"),
    path('form_del_emergencia/<id>',form_del_emergencia,name="form_del_emergencia"),
    path('form_emergencia',form_emergencias,name="form_emergencia"),
]